import './globals.css'
import type { Metadata } from 'next'
import TopMenu from '@/components/TopMenu'
// import NextAuthProvider from './providers/NextAuthProvider'
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import NextAuthProvider from '@/providers/NextAuthProvider';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className='font-sans '>
          <NextAuthProvider session={session}>
            <TopMenu/>
            {children}
          </NextAuthProvider>
      </body>
    </html>
  )
}
